[project]
name = "mcp-server-example"
version = "0.1.0"
description = "A learning repository for Model Context Protocol's server-side via Python."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.4.1",
]
